UnitedWay/Controllers/HeroRewardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitedWay.Controllers
{
    [Authorize]
    public class HeroRewardsController : Controller
    {
        // GET: HeroRewards
        public ActionResult Index()
        {
            return View();
        }
    }
}

UnitedWay/Controllers/VolunteerEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitedWay.Models;

namespace UnitedWay.Controllers
{
    public class VolunteerEventsController : Controller
    {
        private ApplicationDbContext _context;

        public VolunteerEventsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: VolunteerEvents
        public ActionResult Index()
        {
            List<VolunteerEvent> volunteerEvents = _context.VolunteerEvents.ToList();
            return View(volunteerEvents);
        }

        public ActionResult Confirmation()
        {
            return View();
        }

        public ActionResult Details(int id)
        {   
            return View(_context.VolunteerEvents.Single(v => v.Id == id));
        }
    }
}

UnitedWay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - United Way of Delaware</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top veryblue">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Join UW HeroRewards!", "Index", "HeroRewards", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Donations", "Index", "Donations")</li>
                    <li>@Html.ActionLink("Volunteer Opportunities", "Index", "VolunteerEvents")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My United Way Web Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>