UnitedWay/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnitedWay.Models
{
    public class Donation
    {
        [Required]
        public double Amount { get; set; }
        [Required]
        public int Id { get; set; }
        [Required]
        public string UserId { get; set; }
    }
}

UnitedWay/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using UnitedWay.Models;

namespace UnitedWay.Controllers
{
    public class DonationsController : Controller
    {
        ApplicationDbContext _context;

        public DonationsController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Donations
        public ActionResult Index()
        {
            Donation donation = new Donation()
                                {
                                    UserId = System.Web.HttpContext.Current.User.Identity.GetUserId()
                                };
            return View(donation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Donation donation)
        {
            if(!ModelState.IsValid)
                return View("Index", donation);
            _context.Donations.Add(donation);
            _context.SaveChanges();
            return View("Confirmation");
        }

        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

UnitedWay/Views/Donations/Confirmation.cshtml
@{
    ViewBag.Title = "Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation</h2>

<h1>Thank you so much for your donation!</h1>

<img src="http://media1.myfolio.com/users/donatewale/images/l0tcji7p70.jpg" />
<p> <a href="/VolunteerEvents">Here's more ways to contribute</a></p>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1052054614892979',
      xfbml      : true,
      version    : 'v2.8'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

UnitedWay/Views/Donations/Index.cshtml
@model UnitedWay.Models.Donation
@{
    ViewBag.Title = "Make a Donation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Make a Donation. 
    <br />Be Apart of Change.</h2<br /><br />

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQEFtecRfUZh2Uyl-rkyktI6M_497PVE7J4MIF_TDaqpx4aUlALs3OJBw"<br />
<br />

@using (Html.BeginForm("Save", "Donations"))
{
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">$</span>
            @Html.TextBoxFor(m => m.Amount, new {@class="form-control", placeholder="Donation amount"})
        </div>
        @Html.ValidationMessageFor(m => m.Amount)
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}

<div class="row">
    <div class="col-md-4">

        <a href="/Home/About"><img src="http://i318.photobucket.com/albums/mm407/desbby13/about.jpg" border="0" width="150" height="150" /></a>
        <a href="Home/"><img src="http://i318.photobucket.com/albums/mm407/desbby13/home.jpg" border="0" width="150" height="150" /></a>
        <a href="/VolunteerEvents"><img src="http://i318.photobucket.com/albums/mm407/desbby13/volunteer.jpg" border="0" width="150" height="150" /></a>
        <!--<a href="/Donations"><img src="http://i318.photobucket.com/albums/mm407/desbby13/donate.jpg" border="0" width="150" height="150" /></a>-->
        <a href="/HeroRewards"><img src="http://i318.photobucket.com/albums/mm407/desbby13/herorewards.jpg" border="0" width="150" height="150" /></a>


        <a href="/Home/Contact"><img src="http://i318.photobucket.com/albums/mm407/desbby13/contact.jpg" border="0" width="150" height="150" /></a>

    </div>
</div>